#!/usr/bin/env bash
# Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."


# Install homebrew packages
if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
    brew bundle check >/dev/null 2>&1  || {
        echo "==> Installing Homebrew dependencies…"
        brew bundle
    }
fi


# Install Python using pyenv
if [ -f ".python-version" ] && [ -z "$(pyenv --version 2>/dev/null)" ]; then
    echo "==> Installing Python…"
    pyenv install --skip-existing
fi


# Intall Python dependencies

# Ensure that packages are only installed in an active virtual environment
export PIP_REQUIRE_VIRTUALENV=true

# Prefer use of a Pipfile and pipenv for dependency and environment managment management
if [ -f "Pipfile" ] && [ -n "$(pipenv --version 2>/dev/null)" ]; then
    echo "==> Installing Python dependencies from Pipfile using pipenv..."
    pipenv install --dev

elif [ -f "requirements.txt" ] || [ -f "requirements-dev.txt" ]; then
    echo "==> Installing Python dependencies from requirements file(s) using pip"

    # Check for an active virtual environment, or look for one in the project directory
    echo "Looking for a Python virtual environment..."
    if [ -n "$(python -c 'import sys; print (sys.real_prefix)' 2>/dev/null)" ]; then
        echo "Installing packages in the active virtual environment."
    elif [ -f "venv/bin/activate" ]; then
        echo "Installing packages in the project's venv virtual environment."
        # shellcheck disable=SC1091
        source venv/bin/activate
    elif [ -f ".venv/bin/activate" ]; then
        echo "Installing packages in the project's .venv virtual environment."
        # shellcheck disable=SC1091
        source .venv/bin/activate
    fi

    if [ -f "requirements.txt" ]; then
        echo "Installing Python dependencies from requirements.txt..."
        pip install -r requirements.txt
    fi

    if [ -f "requirements-dev.txt" ]; then
        echo "Installing Python dependencies from requirements-dev.txt..."
        pip install -r requirements-dev.txt
    fi
fi
