#!/usr/bin/env bash
# Launch a console for the application. Optionally allow an environment to be 
# passed in to let the script handle the specific requirements for connecting 
# to a console for that environment.

set -e

cd "$(dirname "$0")/.."

# Use first argument as an environment name. Use this to decide how to connect 
# to the appropriate console.
console=${1:-"dev"}

case ${console} in
    dev)
    echo "==> Connecting to the development console"
    if [ -f "script/console.py" ]; then
        ipython -i script/console.py
    fi
    ;;

    stage)
    echo "==> Connecting to the staging console"
    ;;

    prod)
    echo "==> Connecting to the production console"
    ;;

    *)
    echo "Unknown Console: ${console}"
    exit 1
    ;;
esac
