#!/usr/bin/env bash
# Launch the application and any extra required processes locally.

set -e

cd "$(dirname "$0")/.."

# Ensure everything in the app is up to date.
script/update

# Start the application
