#!/usr/bin/env bash
# Set up application for the first time after cloning, or set it back to the 
# initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/clean --deep
script/bootstrap

# Setup the application for initial use

echo "==> App is now ready to go!"
