#!/usr/bin/env bash
# Run the test suite for the application. Optionally pass in a path to an 
# individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

# Run all tests by default
default=true
test_targets=()


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        lint)
        lint=true
        default=
        ;;

        tests)
        tests=true
        default=
        ;;

        *)
        # Check to see if arguments are paths to target files or directories
        if [ -f ${i} ] || [ -d ${i} ]; then
            test_targets+=(${i})
        else
            echo "Unknown argument: $i"
            exit 1
        fi
        ;;
    esac
done
if [ ! -z ${test_targets} ]; then
    echo "Found Targets: ${test_targets[@]}"
fi


script/clean tests


APP_ENV=${APP_ENV:-"development"}
case ${APP_ENV} in
    development)
    echo "==> Setting up the development environment"
    ;;

    ci)
    echo "==> Setting up the continuous integration environment"
    ;;

    stage)
    echo "==> Setting up the staging environment"
    ;;

    prod)
    echo "==> Setting up the production environment"
    ;;

    *)
    echo "Unknown Application Environment: ${console}"
    exit 1
    ;;
esac


# If debugging, display environment variables
[ -z "$DEBUG" ] || set -x


# Lint the source code
if [ ${default} ] || [ ${lint} ]; then
    echo "==> Linting the source code..."
    flake8 ${test_targets[@]}
fi


# Run the test suite
if [ ${default} ] || [ ${tests} ]; then
    echo "==> Running the test suite..."
    pytest ${test_targets[@]}
fi
